export { sessionRoutes } from "./session.routes.js";
export { colaboratorRoutes } from "./colaborator.routes.js";
export { companyRoutes } from "./company.routes.js";
export { tagRoutes } from "./tag.routes.js";
export { eventRoutes } from "./event.routes.js";
export { commentRoutes } from "./comment.routes.js";
export { registerToEventRoutes } from "./registerToEvent.routes.js";
export { awardRoutes } from "./award.routes.js";
export { pointsRoutes } from "./points.routes.js";